kind: Deployment
apiVersion: apps/v1
metadata:
  name: ftweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ftweb
  template:
    metadata:
      labels:
        app: ftweb
    spec:
      containers:
        - name: ftweb
          image: ftweb:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "300m"
            limits:
              memory: "200Mi"
              cpu: "600m"
---
kind: Service
apiVersion: v1
metadata:
  name: ftweb
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: ftweb
