kind: Deployment
apiVersion: apps/v1
metadata:
  name: minikube-reactjs-feature-flags
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikube-reactjs-feature-flags
  template:
    metadata:
      labels:
        app: minikube-reactjs-feature-flags
    spec:
      containers:
        - name: minikube-reactjs-feature-flags
          image: react-js-feature:1.0.0-prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "300m"
            limits:
              memory: "200Mi"
              cpu: "600m"
---
kind: Service
apiVersion: v1
metadata:
  name: minikube-reactjs-feature-flags
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: minikube-reactjs-feature-flags
